### PR TITLE
Avoid SSR flickering (fix issue #163) and add docstrings

### PR DESCRIPTION
**Pull request by hirschmann**
This PR fixes issue #163 and adds more comments and documentation to pid_arduino-py and pid_autotune.py.

### CODE REVIEW

**Comment by arcidodo** [comment]
i pulled this brance but i get an error if i use pidarduinologic 

```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/craftbeerpi/brewapp/base/automatic/automaticlogic.py", line 73, in pidWrapper
    p.run()
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_arduino.py", line 31, in run
    heat_percent = pid.calc(self.getCurrentTemp(), self.getTargetTemp())
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_arduino.py", line 96, in calc
    now = self._time() * 1000
TypeError: 'module' object is not callable
```

And if i use PIDAutotuneLogic

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/craftbeerpi/brewapp/base/automatic/automaticlogic.py", line 73, in pidWrapper
    p.run()
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_autotune.py", line 33, in run
    while self.isRunning() and not atune.run(self.getCurrentTemp()):
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_autotune.py", line 168, in run
    now = self._time() * 1000
AttributeError: 'PIDAutotune' object has no attribute '_time'
```

**Comment by hirschmann** [comment]
Thanks for testing! The error you mentioned should be fixed now.

**Comment by arcidodo** [comment]
same issue 
```
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/craftbeerpi/brewapp/base/automatic/automaticlogic.py", line 73, in pidWrapper
    p.run()
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_arduino.py", line 31, in run
    heat_percent = pid.calc(self.getCurrentTemp(), self.getTargetTemp())
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_arduino.py", line 96, in calc
    now = self._time() * 1000
TypeError: 'module' object is not callable
```


```
 Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/craftbeerpi/brewapp/base/automatic/automaticlogic.py", line 73, in pidWrapper
    p.run()
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_autotune.py", line 33, in run
    while self.isRunning() and not atune.run(self.getCurrentTemp()):
  File "/home/pi/craftbeerpi/brewapp/base/automatic/pid_autotune.py", line 168, in run
    now = self._time() * 1000
AttributeError: 'PIDAutotune' object has no attribute '_time'
```

i'm sure that im on the latest pull 

```
pi@raspberrypi:~/craftbeerpi $ sudo git show
commit 952fb1c9ebdff066c6a1a9d46d02d7a80967aee7
Author: Stefan Hirschmann <st.hirschmann@t-online.de>
Date:   Tue Apr 11 12:58:46 2017 +0200

    Fix imports
```

**Comment by hirschmann** [comment]
I tried to update pid_autotune and pid_arduino by merging my updated versions from https://github.com/hirschmann/pid-autotune into craftbeerpi.
Unfortunately I fucked it up, sorry.

I'm going to close this PR and create a new one tomorrow.

**Pull request closed without merging**
