### PR TITLE
Added Hendi support

### PR DESCRIPTION
**Pull request by AHm74**
Added first version of support for Hendi induction cooker. 
hendipid - used for controlling the temperature with a PID controller
hendipowerctrl - used for controlling the power of the cooker the power is controlled by setting a "temperature" which is converted into a PWM that corresponds to a power output.

### CODE REVIEW

**Comment by ollinator2000** [comment]
Hi ,
i m using a wendi induction cooker 3,5KW digital . how do you control the cooker ? may be you can give me a short doc , i m very interested in automated heating the kettle ... ;-) 


Regards 
Olli

**Comment by Manuel83** [comment]
Thanks for providing this extension. Because it's more complex I like to test this logic before the merge. I will do this next week.

Regards,
Manuel

**Comment by AHm74** [comment]
@ollinator2000 I have the analogue version of the Hendi cooker (with potentiometer) I've made a [PCB](https://shbf.se/bryggaren/download/file.php?id=1866&mode=view) with opto coulers to isolate the RPi from the Hendi (yes it's necessary, I've burned one set of RPi, 7" display and Hendi) I if you use google translate on the following [thread](https://shbf.se/bryggaren/viewtopic.php?f=6&t=11762) my first post is [this one](https://shbf.se/bryggaren/viewtopic.php?f=6&t=11762&start=60#p72929). I'm using the same PCB when I'm using CBP.

**Comment by Manuel83** [comment]
I'm currently testing the code. Not sure if I understand this
You are using some PWM feature and switching the heater on and off? 
How is the Hendi Cooker wired to the Raspberry Pi? 

```GPIO.setmode(GPIO.BCM)
       
        GPIO.setup(self.config["Hendi_Power_GPIO"],GPIO.OUT)
        pwm=GPIO.PWM(self.config["Hendi_Power_GPIO"],100)
        pwm.start(0)

        while self.isRunning():
            heat_percent = pid.calc(self.getCurrentTemp(), self.getTargetTemp())

            # WHAT IS THIS DONG???
            pwm.ChangeDutyCycle(heat_percent)

            if heat_percent == 0:
                self.switchHeaterOFF()
            else:
                self.switchHeaterON()

            socketio.sleep(ts)
```

**Comment by AHm74** [comment]
To control the Hendi you first need to swich the coocker on/off, this is done by the self.switchHeaterON()/ self.switchHeaterOFF() (via opto coupler). When switched on the power is adjusted with a 0-5V signal which is generated by sending the PWM through a LP-filter via an opto coupler, see [schematic](https://shbf.se/bryggaren/download/file.php?id=1866&mode=view).

**Comment by Manuel83** [comment]
Ok now I got it. I added a small try catch block and merged it to the master. 
That's a quite advanced topic. Could you provide some guide how to use it?

Regards,
Manuel

**Comment by AHm74** [comment]
Started to write a howto in the [wiki section](https://github.com/Manuel83/craftbeerpi/wiki/Hendi-Induction-cooker-model-3500-M--Setup)

**Comment by Manuel83** [comment]
Thats cool! Thank you very much. I will post this new feature the next days on facebook and to the CBPi User group

**Pull request merged**
