### PR TITLE
Add PID autotune and PID controller

### PR DESCRIPTION
**Pull request by hirschmann**
I've created a PID controller based on [Arduino-PID-Library](https://github.com/br3ttb/Arduino-PID-Library), because the PID controller which comes with craftbeerpi produces too much overshoot (for my setup) regardless the selected parameters.
The Arduino PID responds to parameter changes like expected and there is a really good explanation of how it works by the author of the original lib: http://brettbeauregard.com/blog/2011/04/improving-the-beginners-pid-introduction/
The PID logic can be selected and configured similar to the default PID logic.

I've also added a PID autotune logic based on [Arduino-PID-AutoTune-Library](https://github.com/t0mpr1c3/Arduino-PID-AutoTune-Library) and a custom tuning rule (named 'brewing') which calculates PID parameters which produce as little overshoot as possible for a inert system like a brewing kettle (only tested on my own setup though).
There is also a explanation of how the autotune logic works by the author of the original lib: http://brettbeauregard.com/blog/2012/01/arduino-pid-autotune-library/

You can autotune your system following these steps:
1. Select pid_autotune logic as automatic logic for your kettle
2. Set a temperature setpoint. Usually something between 50C to 60C works well.
3. Enable automatic control
4. Wait until the autotune logic disables automatic control itself. This can take up to an hour or more (depending on the individual hardware setup and the setpoint temperature), because the autotune logic tries to oscillate around the setpoint. The problem is, that after overshooting the setpoint, it has to wait until the temperature drops below the setpoint which usually takes some time. 
5. The results will be saved to a file named `pidparams.txt` in the craftbeerpi working directory (usually: `craftbeerpi/pidparams.txt`)

_edit:_
In order to help users to tune the PID-controller for their brewing setup, I've created a [**PID-controller/brewing kettle simulation**](https://github.com/hirschmann/pid-autotune).

### CODE REVIEW

**Comment by Abyssal21** [comment]
Thanks for adding this! I have a question: what is the ".gitignore" file you are editing and where can I find it? I know the other 3 files, but not the ".gitignore".

**Comment by Abyssal21** [comment]
I am not familiar with the .gitignore file so after Googling it I created a file in the ".git" folder of the crafterbeerpi folder titled ".gitignore". Did I do this correctly? I'm asking because after trying to implement these I received a connection error after rebooting my Pi and trying to start CBP

**Comment by Ph03n1X1** [comment]
So, in order to use this, I am assuming you need to add an Arduino to the CBPi hardware and connect the temp probes to this rather than to the Pi. Do you have any references for this modification? Will the other automatic methods still be able to access the temp probes to work correctly?

Also, does the pid_arduino automatic control method automatically use the parameters file generated by the autotune, or do you need to manually read these settings out of the file and input them into the pid_arduino automatic control?

**Comment by hirschmann** [comment]
@Abyssal21 
Now that the pull request has been merged, you can pull in the changes via `git pull`
The .gitignore file is hidden because it's a [dotfile](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory).

@Ph03n1X1 
No, you don't need an Arduino. I named the logic pid_arduino to distinguish it from craftbeerpi's default PID logic and because it's basically a python port of  Arduino-PID-Library with some changes/improvements.
You can select pid_arduino automatic logic just like any other automatic logic. All other methods can still access temp probes and work correctly.

The pid_arduino logic ignores the parameters file. You have to manually read and input them.

**Comment by Ph03n1X1** [comment]
Perfect. Thanks!

**Comment by Abyssal21** [comment]
When I used the PID Arduino my element never turned off after it passed the target temp. I used the autotune logic first and used pid parameters as the inputs for the PID Arduino.

**Comment by lorenznijs** [comment]
What do I fill in for the output % when I want to run autotune? do I keep it both at 100 or do i change the first one to the amount of power that I want to use when it's reached the target temperature?

**Comment by hirschmann** [comment]
Usually keeping max. output at 100% is ok.

Effectively, the _max. output %_ setting is limiting your heater's maximum power output, e.g. if you set it to 80%, the heater will never output more than 80% of its power.
This is useful if the temperature rises too fast (as a rule of thumb: 1 degree per minute is considered ideal) because your heater is too powerful.

So, if you're planning to run the pid_arduino logic with a max. output setting of 80%, you should also tune with a max. output of 80%.

**Comment by April15Hater** [comment]
I'm getting an error when I try to run this:

pi@Marbrew:~/pid-autotune $ python sim.py --atune --volume 35.1 --power 6.5
  File "sim.py", line 41
SyntaxError: Non-ASCII character '\xc2' in file sim.py on line 41, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by hirschmann** [comment]
*sim.py* requires python3, you're probably trying to run it on python2

**Pull request merged**
